development:
  server: "https://faye-conquerup.herokuapp.com/faye/faye"
  secret_token: batkaro
test:
  server: "https://faye-conquerup.herokuapp.com/faye/test"
  secret_token: <%= ENV['FAYE'] %>
production:
  server: "https://faye-conquerup.herokuapp.com/faye"
  secret_token: <%= ENV['FAYE'] %>
  signature_expiration: 3600 # one hour